# Generated by Django 2.2.2 on 2019-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190606_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Service'), (1, 'Benefit'), (2, 'Team Player')])),
                ('ordered_value', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordered_value', 'pk'),
            },
        ),
    ]
