# Generated by Django 2.2.2 on 2019-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('ordering_value', 'pk')},
        ),
        migrations.RenameField(
            model_name='chunk',
            old_name='ordered_value',
            new_name='ordering_value',
        ),
        migrations.AlterField(
            model_name='chunk',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Service'), (1, 'Benefit'), (2, 'Team Player'), (3, 'Contact')]),
        ),
    ]
