# Generated by Django 2.2.2 on 2019-06-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190610_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
