# Generated by Django 2.2.2 on 2019-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190610_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='special_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Service'), (1, 'Benefit'), (2, 'Team Player'), (3, 'Contact'), (4, 'Social Contact')]),
        ),
    ]
