# Generated by Django 2.2.2 on 2019-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190610_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
