# Generated by Django 2.2.2 on 2019-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190611_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8),
        ),
    ]
