# Generated by Django 2.2.2 on 2019-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('ordering_value', 'pk')},
        ),
        migrations.AddField(
            model_name='project',
            name='ordering_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
